// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: chatbothub.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Chatbothub {
  public static partial class ChatBotHub
  {
    static readonly string __ServiceName = "chatbothub.ChatBotHub";

    static readonly grpc::Marshaller<global::Chatbothub.EventRequest> __Marshaller_chatbothub_EventRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.EventRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Chatbothub.EventReply> __Marshaller_chatbothub_EventReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.EventReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Chatbothub.BotsRequest> __Marshaller_chatbothub_BotsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.BotsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Chatbothub.BotsReply> __Marshaller_chatbothub_BotsReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.BotsReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Chatbothub.LoginQQRequest> __Marshaller_chatbothub_LoginQQRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.LoginQQRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Chatbothub.LoginQQReply> __Marshaller_chatbothub_LoginQQReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Chatbothub.LoginQQReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Chatbothub.EventRequest, global::Chatbothub.EventReply> __Method_EventTunnel = new grpc::Method<global::Chatbothub.EventRequest, global::Chatbothub.EventReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "EventTunnel",
        __Marshaller_chatbothub_EventRequest,
        __Marshaller_chatbothub_EventReply);

    static readonly grpc::Method<global::Chatbothub.BotsRequest, global::Chatbothub.BotsReply> __Method_GetBots = new grpc::Method<global::Chatbothub.BotsRequest, global::Chatbothub.BotsReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetBots",
        __Marshaller_chatbothub_BotsRequest,
        __Marshaller_chatbothub_BotsReply);

    static readonly grpc::Method<global::Chatbothub.LoginQQRequest, global::Chatbothub.LoginQQReply> __Method_LoginQQ = new grpc::Method<global::Chatbothub.LoginQQRequest, global::Chatbothub.LoginQQReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoginQQ",
        __Marshaller_chatbothub_LoginQQRequest,
        __Marshaller_chatbothub_LoginQQReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Chatbothub.ChatbothubReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ChatBotHub</summary>
    public abstract partial class ChatBotHubBase
    {
      public virtual global::System.Threading.Tasks.Task EventTunnel(grpc::IAsyncStreamReader<global::Chatbothub.EventRequest> requestStream, grpc::IServerStreamWriter<global::Chatbothub.EventReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Chatbothub.BotsReply> GetBots(global::Chatbothub.BotsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Chatbothub.LoginQQReply> LoginQQ(global::Chatbothub.LoginQQRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ChatBotHub</summary>
    public partial class ChatBotHubClient : grpc::ClientBase<ChatBotHubClient>
    {
      /// <summary>Creates a new client for ChatBotHub</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChatBotHubClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ChatBotHub that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChatBotHubClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChatBotHubClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChatBotHubClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Chatbothub.EventRequest, global::Chatbothub.EventReply> EventTunnel(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return EventTunnel(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Chatbothub.EventRequest, global::Chatbothub.EventReply> EventTunnel(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_EventTunnel, null, options);
      }
      public virtual global::Chatbothub.BotsReply GetBots(global::Chatbothub.BotsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBots(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Chatbothub.BotsReply GetBots(global::Chatbothub.BotsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetBots, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Chatbothub.BotsReply> GetBotsAsync(global::Chatbothub.BotsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetBotsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Chatbothub.BotsReply> GetBotsAsync(global::Chatbothub.BotsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetBots, null, options, request);
      }
      public virtual global::Chatbothub.LoginQQReply LoginQQ(global::Chatbothub.LoginQQRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginQQ(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Chatbothub.LoginQQReply LoginQQ(global::Chatbothub.LoginQQRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoginQQ, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Chatbothub.LoginQQReply> LoginQQAsync(global::Chatbothub.LoginQQRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginQQAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Chatbothub.LoginQQReply> LoginQQAsync(global::Chatbothub.LoginQQRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoginQQ, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChatBotHubClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChatBotHubClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChatBotHubBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_EventTunnel, serviceImpl.EventTunnel)
          .AddMethod(__Method_GetBots, serviceImpl.GetBots)
          .AddMethod(__Method_LoginQQ, serviceImpl.LoginQQ).Build();
    }

  }
}
#endregion
